# Generated by Django 4.2.5 on 2023-09-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_file_created_alter_file_file_alter_file_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
