# Generated by Django 4.2.5 on 2023-09-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_text_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Текст'},
        ),
    ]
