# Generated by Django 4.2.5 on 2023-09-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_content_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={},
        ),
    ]
