# Generated by Django 4.2.5 on 2023-09-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_text_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={},
        ),
    ]
