# Generated by Django 4.2.5 on 2023-09-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_text_options_alter_image_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео'},
        ),
    ]
